### ISSUE TITLE
TypeError: _.compose is not a function

### ISSUE THREAD

**Issue by chenatu** [anryko/grafana-influx-dashboard#75]
For grafana version 4.0.0 beta in console it caused this error when load getdash.js:
````
boot.f5ee487b.js:5 Potentially unhandled rejection [1] TypeError: _.compose is not a function
    at getDashApp (<anonymous>:554:20)
    at eval (eval at <anonymous> (http://192.168.20.57:3000/public/app/boot.f5ee487b.js:11:18558), <anonymous>:63:16)
    at O (http://192.168.20.57:3000/public/app/boot.f5ee487b.js:6:1679)
    at K (http://192.168.20.57:3000/public/app/boot.f5ee487b.js:6:1311)
    at y.when (http://192.168.20.57:3000/public/app/boot.f5ee487b.js:6:4985)
    at v.run (http://192.168.20.57:3000/public/app/boot.f5ee487b.js:6:4021)
    at a._drain (http://192.168.20.57:3000/public/app/boot.f5ee487b.js:5:27943)
    at drain (http://192.168.20.57:3000/public/app/boot.f5ee487b.js:5:27597)
    at MutationObserver.b (http://192.168.20.57:3000/public/app/boot.f5ee487b.js:5:29518)
````
How to fix this?

**Comment by anryko** [comment]
Hi @chenatu 

Right..., checked it out. They finally moved away from lodash 2.4  to 4.15! I'll add grafana4 support soon.

**Comment by anryko** [comment]
OK. We left Grafana3 behind in ```grafana3.1_influxdb1.0``` branch and now ```master``` is on Grafana4 beta.
